export const CREATE_BLOG_CATEGORY_REQUEST='CREATE_BLOG_CATEGORY_REQUEST';
export const CREATE_BLOG_CATEGORY_SUCCESS='CREATE_BLOG_CATEGORY_SUCCESS';
export const CREATE_BLOG_CATEGORY_FAILURE='CREATE_BLOG_CATEGORY_FAILURE';

export const GETBLOG_CATEGORY_REQUEST='GETBLOG_CATEGORY_REQUEST';
export const GETBLOG_CATEGORY_SUCCESS='GETBLOG_CATEGORY_SUCCESS';
export const GETBLOG_CATEGORY_FAILURE='GETBLOG_CATEGORY_FAILURE';


export const DELETE_BLOG_CATEGORY_REQUEST="DELETE_BLOG_CATEGORY_REQUEST";
export const DELETE_BLOG_CATEGORY_SUCCESS="DELETE_BLOG_CATEGORY_SUCCESS";
export const DELETE_BLOG_CATEGORY_FAIL="DELETE_BLOG_CATEGORY_FAIL";

export const BLOG_CATEGORY_RESET_CLEAR = 'BLOG_CATEGORY_RESET_CLEAR';

