export const CREATE_BLOG_REQUEST='CREATE_BLOG_REQUEST';
export const CREATE_BLOG_SUCCESS='CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAILURE='CREATE_BLOG_FAILURE';

export const GETBLOG_REQUEST='GETBLOG_REQUEST';
export const GETBLOG_SUCCESS='GETBLOG_SUCCESS';
export const GETBLOG_FAILURE='GETBLOG_FAILURE';

export const GET_SINGLE_BLOG_REQUEST='GET_SINGLE_BLOG_REQUEST';
export const GET_SINGLE_BLOG_SUCCESS='GET_SINGLE_BLOG_SUCCESS';
export const GET_SINGLE_BLOG_FAILURE='GET_SINGLE_BLOG_FAILURE';

export const GET_BLOG_BY_CATEGORY_REQUEST='GET_BLOG_BY_CATEGORY_REQUEST';
export const GET_BLOG_BY_CATEGORY_SUCCESS='GET_BLOG_BY_CATEGORY_SUCCESS';
export const GET_BLOG_BY_CATEGORY_FAILURE='GET_BLOG_BY_CATEGORY_FAILURE';

export const UPDATE_BLOG_REQUEST="UPDATE_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS="UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_FAIL="UPDATE_BLOG_FAIL";

export const DELETE_BLOG_REQUEST="DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS="DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL="DELETE_BLOG_FAIL";

export const RESET_CLEAR = 'RESET_CLEAR';

