export const CREATE_FORM_REQUEST='CREATE_FORM_REQUEST';
export const CREATE_FORM_SUCCESS='CREATE_FORM_SUCCESS';
export const CREATE_FORM_FAILURE='CREATE_FORM_FAILURE';

export const GETFORM_REQUEST='GETFORM_REQUEST';
export const GETFORM_SUCCESS='GETFORM_SUCCESS';
export const GETFORM_FAILURE='GETFORM_FAILURE';

export const GET_SINGLE_FORM_REQUEST='GET_SINGLE_FORM_REQUEST';
export const GET_SINGLE_FORM_SUCCESS='GET_SINGLE_FORM_SUCCESS';
export const GET_SINGLE_FORM_FAILURE='GET_SINGLE_FORM_FAILURE';

export const DELETE_FORM_REQUEST="DELETE_FORM_REQUEST";
export const DELETE_FORM_SUCCESS="DELETE_FORM_SUCCESS";
export const DELETE_FORM_FAIL="DELETE_FORM_FAIL";

export const CONTACT_RESET_CLEAR = 'CONTACT_RESET_CLEAR';

