export const CREATE_EVENTS_REQUEST='CREATE_EVENTS_REQUEST';
export const CREATE_EVENTS_SUCCESS='CREATE_EVENTS_SUCCESS';
export const CREATE_EVENTS_FAILURE='CREATE_EVENTS_FAILURE';

export const GETEVENTS_REQUEST='GETEVENTS_REQUEST';
export const GETEVENTS_SUCCESS='GETEVENTS_SUCCESS';
export const GETEVENTS_FAILURE='GETEVENTS_FAILURE';

export const GET_SINGLE_EVENTS_REQUEST='GET_SINGLE_EVENTS_REQUEST';
export const GET_SINGLE_EVENTS_SUCCESS='GET_SINGLE_EVENTS_SUCCESS';
export const GET_SINGLE_EVENTS_FAILURE='GET_SINGLE_EVENTS_FAILURE';

export const UPDATE_EVENTS_REQUEST="UPDATE_EVENTS_REQUEST";
export const UPDATE_EVENTS_SUCCESS="UPDATE_EVENTS_SUCCESS";
export const UPDATE_EVENTS_FAIL="UPDATE_EVENTS_FAIL";

export const DELETE_EVENTS_REQUEST="DELETE_EVENTS_REQUEST";
export const DELETE_EVENTS_SUCCESS="DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FAIL="DELETE_EVENTS_FAIL";

export const EVENT_RESET_CLEAR = 'EVENT_RESET_CLEAR';

