export const CREATE_GALLERY_CATEGORY_REQUEST='CREATE_GALLERY_CATEGORY_REQUEST';
export const CREATE_GALLERY_CATEGORY_SUCCESS='CREATE_GALLERY_CATEGORY_SUCCESS';
export const CREATE_GALLERY_CATEGORY_FAILURE='CREATE_GALLERY_CATEGORY_FAILURE';

export const GET_GALLERY_CATEGORY_REQUEST='GET_GALLERY_CATEGORY_REQUEST';
export const GET_GALLERY_CATEGORY_SUCCESS='GET_GALLERY_CATEGORY_SUCCESS';
export const GET_GALLERY_CATEGORY_FAILURE='GET_GALLERY_CATEGORY_FAILURE';


export const UPDATE_GALLERY_CATEGORY_REQUEST="UPDATE_GALLERY_CATEGORY_REQUEST";
export const UPDATE_GALLERY_CATEGORY_SUCCESS="UPDATE_GALLERY_CATEGORY_SUCCESS";
export const UPDATE_GALLERY_CATEGORY_FAIL="UPDATE_GALLERY_CATEGORY_FAIL";

export const DELETE_GALLERY_CATEGORY_REQUEST="DELETE_GALLERY_CATEGORY_REQUEST";
export const DELETE_GALLERY_CATEGORY_SUCCESS="DELETE_GALLERY_CATEGORY_SUCCESS";
export const DELETE_GALLERY_CATEGORY_FAIL="DELETE_GALLERY_CATEGORY_FAIL";

export const RESET_CLEAR = 'RESET_CLEAR';

