export const CREATE_GALLERY_REQUEST='CREATE_GALLERY_REQUEST';
export const CREATE_GALLERY_SUCCESS='CREATE_GALLERY_SUCCESS';
export const CREATE_GALLERY_FAILURE='CREATE_GALLERY_FAILURE';

export const GET_GALLERY_REQUEST='GET_GALLERY_REQUEST';
export const GET_GALLERY_SUCCESS='GET_GALLERY_SUCCESS';
export const GET_GALLERY_FAILURE='GET_GALLERY_FAILURE';

export const GET_SINGLE_GALLERY_REQUEST='GET_SINGLE_GALLERY_REQUEST';
export const GET_SINGLE_GALLERY_SUCCESS='GET_SINGLE_GALLERY_SUCCESS';
export const GET_SINGLE_GALLERY_FAILURE='GET_SINGLE_GALLERY_FAILURE';

export const GET_GALLERY_BY_CATEGORY_REQUEST='GET_GALLERY_BY_CATEGORY_REQUEST';
export const GET_GALLERY_BY_CATEGORY_SUCCESS='GET_GALLERY_BY_CATEGORY_SUCCESS';
export const GET_GALLERY_BY_CATEGORY_FAILURE='GET_GALLERY_BY_CATEGORY_FAILURE';

export const UPDATE_GALLERY_REQUEST="UPDATE_GALLERY_REQUEST";
export const UPDATE_GALLERY_SUCCESS="UPDATE_GALLERY_SUCCESS";
export const UPDATE_GALLERY_FAIL="UPDATE_GALLERY_FAIL";

export const DELETE_GALLERY_REQUEST="DELETE_GALLERY_REQUEST";
export const DELETE_GALLERY_SUCCESS="DELETE_GALLERY_SUCCESS";
export const DELETE_GALLERY_FAIL="DELETE_GALLERY_FAIL";

export const GALLERY_RESET_CLEAR = 'GALLERY_RESET_CLEAR';

