export const CREATE_PAYMENT_REQUEST='CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_SUCCESS='CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAILURE='CREATE_PAYMENT_FAILURE';

export const VERIFY_PAYMENT_REQUEST='VERIFY_PAYMENT_REQUEST';
export const VERIFY_PAYMENT_SUCCESS='VERIFY_PAYMENT_SUCCESS';
export const VERIFY_PAYMENT_FAILURE='VERIFY_PAYMENT_FAILURE';

export const GET_PAYMENT_REQUEST='GET_PAYMENT_REQUEST';
export const GET_PAYMENT_SUCCESS='GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAILURE='GET_PAYMENT_FAILURE';




export const RESET_CLEAR = 'RESET_CLEAR';

